//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./TinyLisp.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TinyLispParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ITinyLispListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLispParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] TinyLispParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLispParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] TinyLispParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLispParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] TinyLispParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLispParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] TinyLispParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLispParser.quotedList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotedList([NotNull] TinyLispParser.QuotedListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLispParser.quotedList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotedList([NotNull] TinyLispParser.QuotedListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyLispParser.listItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListItems([NotNull] TinyLispParser.ListItemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyLispParser.listItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListItems([NotNull] TinyLispParser.ListItemsContext context);
}
