//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./TinyLisp.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public partial class TinyLispLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BooleanConstant=1, Number=2, ID=3, DoubleQuoteString=4, Quote=5, LeftPeren=6, 
		RightPeren=7, Comment=8, SPACE=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"BooleanConstant", "Number", "ID", "DoubleQuoteString", "Quote", "LeftPeren", 
		"RightPeren", "Comment", "SPACE"
	};


	public TinyLispLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TinyLispLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'''", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BooleanConstant", "Number", "ID", "DoubleQuoteString", "Quote", 
		"LeftPeren", "RightPeren", "Comment", "SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TinyLisp.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static TinyLispLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,9,84,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,29,8,0,1,1,5,1,
		32,8,1,10,1,12,1,35,9,1,1,1,3,1,38,8,1,1,1,4,1,41,8,1,11,1,12,1,42,1,2,
		4,2,46,8,2,11,2,12,2,47,1,3,1,3,1,3,1,3,5,3,54,8,3,10,3,12,3,57,9,3,1,
		3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,5,7,71,8,7,10,7,12,7,74,
		9,7,1,7,1,7,1,8,4,8,79,8,8,11,8,12,8,80,1,8,1,8,0,0,9,1,1,3,2,5,3,7,4,
		9,5,11,6,13,7,15,8,17,9,1,0,5,1,0,48,57,9,0,33,33,35,35,42,43,45,45,47,
		57,61,61,63,63,65,90,97,122,2,0,34,34,92,92,2,0,10,10,13,13,3,0,9,10,13,
		13,32,32,92,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,
		0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,1,28,1,0,0,0,3,37,
		1,0,0,0,5,45,1,0,0,0,7,49,1,0,0,0,9,60,1,0,0,0,11,62,1,0,0,0,13,64,1,0,
		0,0,15,66,1,0,0,0,17,78,1,0,0,0,19,20,5,116,0,0,20,21,5,114,0,0,21,22,
		5,117,0,0,22,29,5,101,0,0,23,24,5,102,0,0,24,25,5,97,0,0,25,26,5,108,0,
		0,26,27,5,115,0,0,27,29,5,101,0,0,28,19,1,0,0,0,28,23,1,0,0,0,29,2,1,0,
		0,0,30,32,7,0,0,0,31,30,1,0,0,0,32,35,1,0,0,0,33,31,1,0,0,0,33,34,1,0,
		0,0,34,36,1,0,0,0,35,33,1,0,0,0,36,38,5,46,0,0,37,33,1,0,0,0,37,38,1,0,
		0,0,38,40,1,0,0,0,39,41,7,0,0,0,40,39,1,0,0,0,41,42,1,0,0,0,42,40,1,0,
		0,0,42,43,1,0,0,0,43,4,1,0,0,0,44,46,7,1,0,0,45,44,1,0,0,0,46,47,1,0,0,
		0,47,45,1,0,0,0,47,48,1,0,0,0,48,6,1,0,0,0,49,55,5,34,0,0,50,54,8,2,0,
		0,51,52,5,92,0,0,52,54,9,0,0,0,53,50,1,0,0,0,53,51,1,0,0,0,54,57,1,0,0,
		0,55,53,1,0,0,0,55,56,1,0,0,0,56,58,1,0,0,0,57,55,1,0,0,0,58,59,5,34,0,
		0,59,8,1,0,0,0,60,61,5,39,0,0,61,10,1,0,0,0,62,63,5,40,0,0,63,12,1,0,0,
		0,64,65,5,41,0,0,65,14,1,0,0,0,66,67,5,59,0,0,67,68,5,59,0,0,68,72,1,0,
		0,0,69,71,8,3,0,0,70,69,1,0,0,0,71,74,1,0,0,0,72,70,1,0,0,0,72,73,1,0,
		0,0,73,75,1,0,0,0,74,72,1,0,0,0,75,76,6,7,0,0,76,16,1,0,0,0,77,79,7,4,
		0,0,78,77,1,0,0,0,79,80,1,0,0,0,80,78,1,0,0,0,80,81,1,0,0,0,81,82,1,0,
		0,0,82,83,6,8,0,0,83,18,1,0,0,0,11,0,28,33,37,42,45,47,53,55,72,80,1,6,
		0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
